### ISSUE TITLE
Inventories Not Switching

### ISSUE THREAD

**Issue by Slothiful** [Gnat008/PerWorldInventory#58]
**Hello!**
Whenever players switch worlds, their inventories do not switch! This plugin is basically useless, but I need it to stop exploits from a temporary creative world to the main survival world. Please help!
**~Slothiful**

#### Config
http://pastebin.com/pqV63Dpe

#### Worlds
http://pastebin.com/z1GhLPX2

**Comment by Gnat008** [comment]
Could you enable debug-logging in the config, reproduce the issue, and attach the log file here?

**Comment by aycgit** [comment]
did u set the permissions right?

**Comment by Slothiful** [comment]
@Gnat I installed Multiverse-Inventories with PerWorldInventory and it works fine, but not without PerWorldInventory. I have no idea why, maybe it's just a simple flaw in the config or worlds file. Also, I will get the logs to you ASAP, I'm very busy at the moment.

@aycgit Didn't exactly know you had to set permissions for your inventories to switch. However, I did disable bypassing so I could deop myself and see. That left me with all permissions but not op. That should have worked.

**Comment by NovaFox161** [comment]
@Slothiful 
I ran into this issue too, I found that by adding all worlds to the worlds yml file fixed it.
I just added all of my worlds to the worlds folder, and put them in their own group (if I didn't want them to share inventories with any other world). Seems to have fixed it right up for now.

Also good to note, I completely disable bypass in the config.yml and never bothered setting up permissions so it must not be a permissions issue.

My config.yml (after my "fix"): http://pastebin.com/KNnRgHDq
My worlds.yml (after my "fix"): http://pastebin.com/2XuKnWZ2

@Gnat008 
 Seems that the "share-if-unconfigured" setting in the config is not checking if it is false (But I may be incorrect on that because even worlds in a group we're sharing with worlds in no group). I have mine set to false in my config and it didn't seem to work, changing to true did nothing either (using PWI 1.7.8 and Spigot 1.10).
Here is the full server log with debug on (before my "fix"): http://pastebin.com/pKTT4epJ
Here is just the PWI debug messages (also before my "fix") (because my server log is very long): http://pastebin.com/Viwg7H2G

I didn't use the debug after I added all of my worlds to the worlds.yml as I found it unneeded because it was sharing and switching inventories correctly. If you need anything else, I would be happy to provide it.

**Comment by Gnat008** [comment]
This should be fixed in the 1.8.0 version of the plugin, which will shortly be released on Spigot. If it still persists, please reopen it.
